api_version = "unstable"

[[extensions]]
name = "GLSPoints"
handle = "glspoints"

uid = "21d3ea46-8557-3b3a-626d-387b6a55ec39befc9305"

type = "function"


  [[extensions.targeting]]
  target = "purchase.pickup-point-delivery-option-generator.fetch"
  input_query = "src/fetch.graphql"
  export = "fetch"

  [[extensions.targeting]]
  target = "purchase.pickup-point-delivery-option-generator.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
